# Day 09. Exercise 02
# Metrics

## 0. Imports

In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
import joblib

## 1. Preprocessing

1. Create the same dataframe as in the previous exercise.
2. Using `train_test_split` with parameters `test_size=0.2`, `random_state=21` get `X_train`, `y_train`, `X_test`, `y_test`. Use the additional parameter `stratify`.

In [32]:
df = pd.read_csv('data/day-of-week-not-scaled.csv')
df.head(5)

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
0,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [33]:
df_1 = pd.read_csv('data/dayofweek.csv')
df['dayofweek'] = df_1['dayofweek']
df.head(5)

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1,dayofweek
0,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
1,2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
2,3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
3,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4

In [34]:
X = df.drop('dayofweek', axis=1)
y = df['dayofweek']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=21)

## 2. SVM

1. Use the best parameters from the previous exercise and train the model of SVM.
2. You need to calculate `accuracy`, `precision`, `recall`, `ROC AUC`.

 - `precision` and `recall` should be calculated for each class (use `average='weighted'`)
 - `ROC AUC` should be calculated for each class against any other class (all possible pairwise combinations) and then weighted average should be applied for the final metric
 - the code in the cell should display the result as below:

```
accuracy is 0.88757
precision is 0.89267
recall is 0.88757
roc_auc is 0.97878
```

In [35]:
svm_model = SVC(C=10, gamma='auto', kernel='rbf', probability=True, random_state=21)
svm_model.fit(X_train, y_train)

svm_predictions = svm_model.predict(X_test)
svm_probabilities = svm_model.predict_proba(X_test)

svm_accuracy = accuracy_score(y_test, svm_predictions)
svm_precision = precision_score(y_test, svm_predictions, average='weighted')
svm_recall = recall_score(y_test, svm_predictions, average='weighted')
svm_roc_auc = roc_auc_score(y_test, svm_probabilities, multi_class='ovo', average='weighted')

print(f'Accuracy is {svm_accuracy:.5f}')
print(f'Precision is {svm_precision:.5f}')
print(f'Recall is {svm_recall:.5f}')
print(f'ROC_AUC is {svm_roc_auc:.5f}')

Accuracy is 0.88757
Precision is 0.89267
Recall is 0.88757
ROC_AUC is 0.97878

## 3. Decision tree

1. The same task for decision tree

In [36]:
tree_model = DecisionTreeClassifier(class_weight='balanced', criterion='gini', max_depth=22, random_state=21)
tree_model.fit(X_train, y_train)

tree_predictions = tree_model.predict(X_test)
tree_probabilities = tree_model.predict_proba(X_test)

tree_accuracy = accuracy_score(y_test, tree_predictions)
tree_precision = precision_score(y_test, tree_predictions, average='weighted')
tree_recall = recall_score(y_test, tree_predictions, average='weighted')
tree_roc_auc = roc_auc_score(y_test, tree_probabilities, multi_class='ovo', average='weighted')

print(f'Accuracy is {tree_accuracy:.5f}')
print(f'Precision is {tree_precision:.5f}')
print(f'Recall is {tree_recall:.5f}')
print(f'ROC_AUC is {tree_roc_auc:.5f}')

Accuracy is 0.89053
Precision is 0.89262
Recall is 0.89053
ROC_AUC is 0.93664

## 4. Random forest

1. The same task for random forest.

In [37]:
rf_model = RandomForestClassifier(max_depth=28, criterion='gini', class_weight=None, n_estimators=50, random_state=21)
rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)
rf_probabilities = rf_model.predict_proba(X_test)

rf_accuracy = accuracy_score(y_test, rf_predictions)
rf_precision = precision_score(y_test, rf_predictions, average='weighted')
rf_recall = recall_score(y_test, rf_predictions, average='weighted')
rf_roc_auc = roc_auc_score(y_test, rf_probabilities, multi_class='ovo', average='weighted')

print(f'Accuracy is {rf_accuracy:.5f}')
print(f'Precision is {rf_precision:.5f}')
print(f'Recall is {rf_recall:.5f}')
print(f'ROC_AUC is {rf_roc_auc:.5f}')

Accuracy is 0.92899
Precision is 0.93009
Recall is 0.92899
ROC_AUC is 0.99033

## 5. Predictions

1. Choose the best model.
2. Analyze: for which `weekday` your model makes the most errors (in % of the total number of samples of that class in your full dataset), for which `labname` and for which `users`.
3. Save the model.

Best model is RandomForest, so we choose it. We already have predictions

In [38]:
df_analysis = pd.DataFrame({
    'test': y_test.values, 
    'pred': rf_predictions
})

full_df = pd.concat((X_test.reset_index(), df_analysis.reset_index()), axis=1)

In [39]:
full_df[~(full_df['test'] == full_df['pred'])]['test'].value_counts().nlargest(1) / len(full_df[full_df['test'] == 0]) * 100

test
0    25.925926
Name: count, dtype: float64

In [40]:
wrong_preds_df = full_df[~(full_df['test'] == full_df['pred'])]
wrong_preds_df = wrong_preds_df.drop(['index', 'numTrials', 'hour', 'test', 'pred'], axis=1)
wrong_preds_df.sum().sort_values(ascending=False).nlargest(7)

labname_project1    9.0
labname_laba04      6.0
uid_user_19         4.0
labname_laba06s     2.0
labname_laba06      2.0
uid_user_3          2.0
uid_user_31         2.0
dtype: float64

In [41]:
joblib.dump(rf_model, 'data/best_model_ex02.gz')

['data/best_model_ex02.gz']

## 6. Function

1. Write a function that takes a list of different models and a corresponding list of parameters (dicts) and returns a dict that contains all the 4 metrics for each model.

In [42]:
def show_metrics(model, params):
    
    try:
        if model == 'SVM':
            svm_model = SVC(C=params['C'], gamma=params['gamma'], kernel=params['kernel'], probability=True, random_state=21)
            svm_model.fit(X_train, y_train)

            predictions = svm_model.predict(X_test)
            probabilities = svm_model.predict_proba(X_test)
        
        elif model == 'DecisionTree':
            tree_model = DecisionTreeClassifier(class_weight=params['class_weight'], criterion=params['criterion'], max_depth=params['max_depth'], random_state=21)
            tree_model.fit(X_train, y_train)

            predictions = tree_model.predict(X_test)
            probabilities = tree_model.predict_proba(X_test)
            
        elif model == 'RandomForest':
            rf_model = RandomForestClassifier(max_depth=params['max_depth'], criterion=params['criterion'], class_weight=params['class_weight'], n_estimators=params['n_estimators'], random_state=21)
            rf_model.fit(X_train, y_train)

            predictions = rf_model.predict(X_test)
            probabilities = rf_model.predict_proba(X_test)
        
        else:
            print('Incorrect model. Try SVM, DecisionTree or RandomForest.')
            return
        
        accuracy = accuracy_score(y_test, predictions)
        precision = precision_score(y_test, predictions, average='weighted')
        recall = recall_score(y_test, predictions, average='weighted')
        roc_auc = roc_auc_score(y_test, probabilities, multi_class='ovo', average='weighted')

        print(f'Accuracy is {accuracy:.5f}')
        print(f'Precision is {precision:.5f}')
        print(f'Recall is {recall:.5f}')
        print(f'ROC_AUC is {roc_auc:.5f}')
        
    except:
        print(f'Incorrect parameters for {model}')

In [43]:
show_metrics('RandomForest', {'max_depth': 28, 'criterion': 'gini', 'class_weight': None, 'n_estimators': 50})

Accuracy is 0.92899
Precision is 0.93009
Recall is 0.92899
ROC_AUC is 0.99033