# Day 09. Exercise 03
# Ensembles

## 0. Imports

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_validate, StratifiedKFold, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier, BaggingClassifier, StackingClassifier
from sklearn.multiclass import OneVsRestClassifier
import joblib

In [2]:
import warnings
warnings.filterwarnings("ignore")

## 1. Preprocessing

1. Create the same dataframe as in the previous exercise.
2. Using `train_test_split` with parameters `test_size=0.2`, `random_state=21` get `X_train`, `y_train`, `X_test`, `y_test` and then get `X_train`, `y_train`, `X_valid`, `y_valid` from the previous `X_train`, `y_train`. Use the additional parameter `stratify`.

In [3]:
df = pd.read_csv('data/day-of-week-not-scaled.csv')
df.head(5)

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
0,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [4]:
df_1 = pd.read_csv('data/dayofweek.csv')
df['dayofweek'] = df_1['dayofweek']
df.head(5)

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1,dayofweek
0,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
1,2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
2,3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
3,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4

In [5]:
X = df.drop('dayofweek', axis=1)
y = df['dayofweek']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=21)

## 2. Individual classifiers

1. Train SVM, decision tree and random forest again with the best parameters that you got from the 01 exercise with `random_state=21` for all of them.
2. Evaluate `accuracy`, `precision`, and `recall` for them on the validation set.
3. The result of each cell of the section should look like this:

```
accuracy is 0.87778
precision is 0.88162
recall is 0.87778
```

In [6]:
svm_model = SVC(C=10, gamma='auto', kernel='rbf', probability=True, random_state=21)

svm_metrics = ['accuracy', 'precision_weighted', 'recall_weighted']
svm_scores = cross_validate(svm_model, X_train, y_train, scoring=svm_metrics, n_jobs=-1)

print(f'Accuracy is {svm_scores['test_accuracy'].mean():.5f}')
print(f'Precision is {svm_scores['test_precision_weighted'].mean():.5f}')
print(f'Recall is {svm_scores['test_recall_weighted'].mean():.5f}')

SyntaxError: f-string: unmatched '[' (432776859.py, line 6)

In [ ]:
tree_model = DecisionTreeClassifier(class_weight='balanced', criterion='gini', max_depth=22, random_state=21)

tree_metrics = ['accuracy', 'precision_weighted', 'recall_weighted']
tree_scores = cross_validate(tree_model, X_train, y_train, scoring=tree_metrics, n_jobs=-1)

print(f'Accuracy is {tree_scores['test_accuracy'].mean():.5f}')
print(f'Precision is {tree_scores['test_precision_weighted'].mean():.5f}')
print(f'Recall is {tree_scores['test_recall_weighted'].mean():.5f}')

SyntaxError: f-string: unmatched '[' (2605510956.py, line 6)

In [ ]:
rf_model = RandomForestClassifier(max_depth=28, criterion='gini', class_weight=None, n_estimators=50, random_state=21)

rf_metrics = ['accuracy', 'precision_weighted', 'recall_weighted']
rf_scores = cross_validate(rf_model, X_train, y_train, scoring=rf_metrics, n_jobs=-1)

print(f'Accuracy is {rf_scores['test_accuracy'].mean():.5f}')
print(f'Precision is {rf_scores['test_precision_weighted'].mean():.5f}')
print(f'Recall is {rf_scores['test_recall_weighted'].mean():.5f}')

SyntaxError: f-string: unmatched '[' (4065178440.py, line 6)

## 3. Voting classifiers

1. Using `VotingClassifier` and the three models that you have just trained, calculate the `accuracy`, `precision`, and `recall` on the validation set.
2. Play with the other parameteres.
3. Calculate the `accuracy`, `precision` and `recall` on the test set for the model with the best weights in terms of accuracy (if there are several of them with equal values, choose the one with the higher precision).

In [ ]:
voting_cf = VotingClassifier(estimators=[('svm', svm_model), ('tree', tree_model), ('rf', rf_model)], n_jobs=-1)

metrics = ['accuracy', 'precision_weighted', 'recall_weighted']
scores = cross_validate(voting_cf, X_train, y_train, scoring=metrics, n_jobs=-1)

print(f'Accuracy is {scores['test_accuracy'].mean():.5f}')
print(f'Precision is {scores['test_precision_weighted'].mean():.5f}')
print(f'Recall is {scores['test_recall_weighted'].mean():.5f}')

SyntaxError: f-string: unmatched '[' (2123167849.py, line 6)

In [ ]:
params = {
    'voting': ['soft', 'hard'],
    'weights': [[i, j, k] for i in range(1, 5) for j in range(1, 5) for k in range(1, 5)]
}

In [ ]:
search_voting = GridSearchCV(VotingClassifier(estimators=[('svm', svm_model), ('tree', tree_model), ('rf', rf_model)], 
                                              n_jobs=-1), param_grid=params)
search_voting.fit(X_train, y_train)

NameError: name 'svm_model' is not defined

In [ ]:
search_voting.best_params_

NameError: name 'search_voting' is not defined

In [ ]:
voting_cf_best = VotingClassifier(estimators=[('svm', svm_model), ('tree', tree_model), ('rf', rf_model)], n_jobs=-1, voting='hard', weights=[2, 3, 2])

metrics = ['accuracy', 'precision_weighted', 'recall_weighted']
scores_soft = cross_validate(voting_cf_best, X_train, y_train, scoring=metrics, n_jobs=-1)

print(f'Accuracy is {scores_soft['test_accuracy'].mean():.5f}')
print(f'Precision is {scores_soft['test_precision_weighted'].mean():.5f}')
print(f'Recall is {scores_soft['test_recall_weighted'].mean():.5f}')

SyntaxError: f-string: unmatched '[' (3420199819.py, line 6)

In [ ]:
voting_cf_best.fit(X_train, y_train)
voting_predictions = voting_cf_best.predict(X_test)

voting_accuracy = accuracy_score(y_test, voting_predictions)
voting_precision = precision_score(y_test, voting_predictions, average='weighted')
voting_recall = recall_score(y_test, voting_predictions, average='weighted')

print(f'Accuracy is {voting_accuracy:.5f}')
print(f'Precision is {voting_precision:.5f}')
print(f'Recall is {voting_recall:.5f}')

NameError: name 'voting_cf_best' is not defined

## 4. Bagging classifiers

1. Using `BaggingClassifier` and `SVM` with the best parameters create an ensemble, try different values of the `n_estimators`, use `random_state=21`.
2. Play with the other parameters.
3. Calculate the `accuracy`, `precision`, and `recall` for the model with the best parameters (in terms of accuracy) on the test set (if there are several of them with equal values, choose the one with the higher precision)

In [ ]:
params = {
    'n_estimators': [10, 30, 50, 100]
}

search_bagging = GridSearchCV(BaggingClassifier(svm_model, n_jobs=-1, random_state=21), param_grid=params)
search_bagging.fit(X_train, y_train)

GridSearchCV(estimator=BaggingClassifier(estimator=SVC(C=10, gamma='auto',
                                                       probability=True,
                                                       random_state=21),
                                         n_jobs=-1, random_state=21),
             param_grid={'n_estimators': [10, 30, 50, 100]})

In [ ]:
search_bagging.best_params_

{'n_estimators': 30}

In [ ]:
bagging_cf = BaggingClassifier(svm_model, n_estimators=30, oob_score=True, random_state=21)
bagging_cf.fit(X_train, y_train)

bagging_predictions = bagging_cf.predict(X_test)
bagging_accuracy = accuracy_score(y_test, bagging_predictions)
bagging_precision = precision_score(y_test, bagging_predictions, average='weighted')
bagging_recall = recall_score(y_test, bagging_predictions, average='weighted')

print(f'Accuracy is {bagging_accuracy:.5f}')
print(f'Precision is {bagging_precision:.5f}')
print(f'Recall is {bagging_recall:.5f}')

Accuracy is 0.89941
Precision is 0.90351
Recall is 0.89941

## 5. Stacking classifiers

1. To achieve reproducibility in this case you will have to create an object of cross-validation generator: `StratifiedKFold(n_splits=n, shuffle=True, random_state=21)`, where `n` you will try to optimize (the details are below).
2. Using `StackingClassifier` and the three models that you have recently trained, calculate the `accuracy`, `precision` and `recall` on the validation set, try different values of `n_splits` `[2, 3, 4, 5, 6, 7]` in the cross-validation generator and parameter `passthrough` in the classifier itself,
3. Calculate the `accuracy`, `precision`, and `recall` for the model with the best parameters (in terms of accuracy) on the test set (if there are several of them with equal values, choose the one with the higher precision). Use `final_estimator=LogisticRegression(solver='liblinear')`.

In [ ]:
estimators = [
    ('svm', svm_model), 
    ('tree', tree_model), 
    ('rf', rf_model)
]

In [ ]:
best = [0, 0]

for i in range(2, 8):
    stacking_model = StackingClassifier(estimators=estimators, passthrough=True, cv=StratifiedKFold(n_splits=i))
    
    metrics = ['accuracy', 'precision_weighted', 'recall_weighted']
    stacking_scores = cross_validate(stacking_model, X_train, y_train, scoring=metrics, n_jobs=-1)
    
    if stacking_scores['test_accuracy'].mean() > best[0]:
        best[0] = stacking_scores['test_accuracy'].mean()
        best[1] = i
    
    print(f'n_splits={i}')
    print(f'Accuracy is {stacking_scores['test_accuracy'].mean():.5f}')
    print(f'Precision is {stacking_scores['test_precision_weighted'].mean():.5f}')
    print(f'Recall is {stacking_scores['test_recall_weighted'].mean():.5f}\n')

print(f'Best score is {best[0]:.4f} for n_splits = {best[1]}')

n_splits=2
Accuracy is 0.90504
Precision is 0.90933
Recall is 0.90504

n_splits=3
Accuracy is 0.90207
Precision is 0.90686
Recall is 0.90207

n_splits=4
Accuracy is 0.90578
Precision is 0.90951
Recall is 0.90578

n_splits=5
Accuracy is 0.90429
Precision is 0.90823
Recall is 0.90429

n_splits=6
Accuracy is 0.90430
Precision is 0.90846
Recall is 0.90430

n_splits=7
Accuracy is 0.90430
Precision is 0.90902
Recall is 0.90430

Best score is 0.9058 for n_splits = 4

In [ ]:
best_stacking_model = StackingClassifier(estimators=estimators, passthrough=True, cv=StratifiedKFold(n_splits=4), 
                                         final_estimator=OneVsRestClassifier(LogisticRegression(solver='liblinear')))
best_stacking_model.fit(X_train, y_train)

stacking_predictions = best_stacking_model.predict(X_test)
stacking_accuracy = accuracy_score(y_test, stacking_predictions)
stacking_precision = precision_score(y_test, stacking_predictions, average='weighted')
stacking_recall = recall_score(y_test, stacking_predictions, average='weighted')

print(f'Accuracy is {stacking_accuracy:.5f}')
print(f'Precision is {stacking_precision:.5f}')
print(f'Recall is {stacking_recall:.5f}')

Accuracy is 0.92899
Precision is 0.93136
Recall is 0.92899

## 6. Predictions

1. Choose the best model in terms of accuracy (if there are several of them with equal values, choose the one with the higher precision).
2. Analyze: for which weekday your model makes the most errors (in % of the total number of samples of that class in your full dataset), for which labname and for which users.
3. Save the model.

In [ ]:
df_analysis = pd.DataFrame({
    'test': y_test.values, 
    'pred': stacking_predictions
})

full_df = pd.concat((X_test.reset_index(), df_analysis.reset_index()), axis=1)

In [ ]:
full_df[~(full_df['test'] == full_df['pred'])]['test'].value_counts().nlargest(1) / len(full_df[full_df['test'] == 0]) * 100

test
1    25.925926
Name: count, dtype: float64

In [ ]:
wrong_preds_df = full_df[~(full_df['test'] == full_df['pred'])]
wrong_preds_df = wrong_preds_df.drop(['index', 'numTrials', 'hour', 'test', 'pred'], axis=1)
wrong_preds_df.sum().sort_values(ascending=False).nlargest(7)

labname_project1    10.0
labname_laba04       6.0
uid_user_19          4.0
uid_user_13          2.0
uid_user_4           2.0
uid_user_3           2.0
labname_laba06       2.0
dtype: float64

In [ ]:
joblib.dump(rf_model, '../data/best_model_ex03.gz')

['../data/best_model_ex03.gz']